# Generated by Django 5.2.17 on 2026-08-23 21:50

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.tenant_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "disputeshield_tenant",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AuditRecord",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.audit_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.BigIntegerField()),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("actor_type", models.CharField(max_length=16)),
                ("actor_id", models.CharField(blank=True, max_length=64)),
                ("actor_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("subject_type", models.CharField(db_index=True, max_length=32)),
                ("subject_id", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("corrects", models.CharField(blank=True, max_length=32)),
                ("prev_hash", models.CharField(max_length=71)),
                ("hash", models.CharField(max_length=71)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_auditrecord",
                "ordering": ["tenant_id", "sequence"],
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["tenant", "subject_type", "subject_id"],
                        name="disputeshie_tenant__6d0396_idx",
                    ),
                    models.Index(
                        fields=["tenant", "occurred_at"], name="disputeshie_tenant__700b70_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "sequence"), name="uniq_audit_sequence_per_tenant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.api_key_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "environment",
                    models.CharField(choices=[("test", "Test"), ("live", "Live")], max_length=8),
                ),
                ("prefix", models.CharField(db_index=True, max_length=16)),
                ("key_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="api_keys",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_apikey",
                "indexes": [
                    models.Index(
                        fields=["prefix", "revoked_at"], name="disputeshie_prefix_3c4293_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.agent_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("display_name", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("compliance", "Compliance"),
                            ("agent", "Agent"),
                            ("read_only", "Read-only"),
                        ],
                        default="agent",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_agent",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "email"), name="uniq_agent_email_per_tenant"
                    )
                ],
            },
        ),
    ]
