# Generated by Django 5.2.17 on 2026-08-23 22:22

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0003_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="SweepHeartbeat",
            fields=[
                ("singleton", models.BooleanField(default=True, primary_key=True, serialize=False)),
                ("last_swept_at", models.DateTimeField()),
                ("last_duration_ms", models.PositiveIntegerField(default=0)),
                ("last_fired_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "disputeshield_sweepheartbeat",
            },
        ),
        migrations.CreateModel(
            name="BusinessCalendar",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.calendar_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("timezone_name", models.CharField(default="UTC", max_length=64)),
                ("always_open", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_businesscalendar",
            },
        ),
        migrations.CreateModel(
            name="BusinessHoursWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="windows",
                        to="disputeshield.businesscalendar",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_businesshourswindow",
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_on", models.DateField()),
                ("name", models.CharField(max_length=128)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holidays",
                        to="disputeshield.businesscalendar",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_holiday",
                "ordering": ["observed_on"],
            },
        ),
        migrations.CreateModel(
            name="NotificationOutbox",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.notification_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("channel", models.CharField(default="email", max_length=16)),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_notificationoutbox",
            },
        ),
        migrations.CreateModel(
            name="SLAClock",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.clock_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_type", models.CharField(default="dispute", max_length=32)),
                ("subject_id", models.CharField(db_index=True, max_length=64)),
                ("started_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("paused_intervals", models.JSONField(default=list)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_slaclock",
            },
        ),
        migrations.CreateModel(
            name="SLADeadline",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.deadline_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("acknowledgement", "Acknowledgement due"),
                            ("resolution", "Resolution due"),
                            ("warning", "Warning threshold"),
                            ("auto_close", "Auto-close due"),
                            ("reopen_window", "Reopen window expires"),
                        ],
                        max_length=24,
                    ),
                ),
                ("threshold_percent", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("fires_at", models.DateTimeField()),
                ("fired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deadlines",
                        to="disputeshield.slaclock",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_sladeadline",
            },
        ),
        migrations.CreateModel(
            name="SLAEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.sla_event_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("acknowledged", "Acknowledged"),
                            ("paused", "Paused"),
                            ("resumed", "Resumed"),
                            ("warned", "Warning threshold crossed"),
                            ("breached", "Breached"),
                            ("stopped", "Stopped"),
                            ("deadlines_recomputed", "Deadlines recomputed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("actor_type", models.CharField(default="system", max_length=16)),
                ("actor_id", models.CharField(blank=True, max_length=64)),
                ("clock_remaining_seconds", models.IntegerField()),
                ("occurred_at", models.DateTimeField()),
                (
                    "clock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="disputeshield.slaclock",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_slaevent",
                "ordering": ["clock_id", "occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.policy_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=64)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_slapolicy",
            },
        ),
        migrations.CreateModel(
            name="SLAPolicyVersion",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.policy_version_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("acknowledgement_minutes", models.PositiveIntegerField(default=60)),
                ("resolution_hours", models.PositiveIntegerField(default=72)),
                ("business_hours_only", models.BooleanField(default=True)),
                ("warning_thresholds", models.JSONField(default=list)),
                ("escalate_at_percent", models.PositiveIntegerField(default=80)),
                ("auto_close_after_hours", models.PositiveIntegerField(default=168)),
                ("reopen_window_hours", models.PositiveIntegerField(default=336)),
                ("regulatory_reference", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.businesscalendar",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="disputeshield.slapolicy",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_slapolicyversion",
                "ordering": ["policy_id", "version"],
            },
        ),
        migrations.AddField(
            model_name="slaclock",
            name="policy_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="disputeshield.slapolicyversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="businesscalendar",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uniq_calendar_name_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="businesshourswindow",
            constraint=models.UniqueConstraint(
                fields=("calendar", "weekday"), name="uniq_window_per_weekday"
            ),
        ),
        migrations.AddConstraint(
            model_name="businesshourswindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("opens_at__lt", models.F("closes_at"))),
                name="window_opens_before_it_closes",
            ),
        ),
        migrations.AddConstraint(
            model_name="holiday",
            constraint=models.UniqueConstraint(
                fields=("calendar", "observed_on"), name="uniq_holiday_per_day"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationoutbox",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["created_at"],
                name="idx_pending_notifications",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationoutbox",
            constraint=models.UniqueConstraint(
                fields=("tenant", "idempotency_key"), name="uniq_notification_per_idempotency_key"
            ),
        ),
        migrations.AddIndex(
            model_name="sladeadline",
            index=models.Index(
                condition=models.Q(("fired_at__isnull", True)),
                fields=["fires_at"],
                name="idx_pending_deadlines",
            ),
        ),
        migrations.AddIndex(
            model_name="sladeadline",
            index=models.Index(
                fields=["tenant", "clock", "kind"], name="disputeshie_tenant__488b2e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sladeadline",
            constraint=models.UniqueConstraint(
                fields=("clock", "kind", "threshold_percent"),
                name="uniq_deadline_per_clock_kind_threshold",
            ),
        ),
        migrations.AddIndex(
            model_name="slaevent",
            index=models.Index(
                fields=["tenant", "kind", "occurred_at"], name="disputeshie_tenant__b62c7d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="slaevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind__in", ["paused", "resumed"]), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="pause_and_resume_carry_a_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="slapolicy",
            constraint=models.UniqueConstraint(
                fields=("tenant", "category"), name="uniq_policy_per_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="slapolicyversion",
            constraint=models.UniqueConstraint(
                fields=("policy", "version"), name="uniq_version_per_policy"
            ),
        ),
        migrations.AddIndex(
            model_name="slaclock",
            index=models.Index(fields=["tenant", "state"], name="disputeshie_tenant__9f6eac_idx"),
        ),
        migrations.AddConstraint(
            model_name="slaclock",
            constraint=models.UniqueConstraint(
                fields=("tenant", "subject_type", "subject_id"), name="uniq_clock_per_subject"
            ),
        ),
    ]
