# Generated by Django 5.2.17 on 2026-08-23 22:36

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers
import disputeshield.models.tenant


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0005_sla_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="customer_ref_salt",
            field=models.CharField(
                default=disputeshield.models.tenant.new_customer_ref_salt,
                editable=False,
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.dispute_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=32)),
                ("customer_ref_hash", models.CharField(db_index=True, max_length=64)),
                ("customer_display_name", models.CharField(blank=True, max_length=128)),
                ("category", models.CharField(db_index=True, max_length=64)),
                ("subcategory", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField()),
                ("transaction_ref", models.CharField(blank=True, db_index=True, max_length=128)),
                ("amount_minor", models.BigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                            ("investigating", "Investigating"),
                            ("awaiting_customer", "Awaiting customer"),
                            ("escalated", "Escalated"),
                            ("resolved", "Resolved"),
                            ("reopened", "Reopened"),
                            ("closed", "Closed"),
                            ("auto_closed", "Auto-closed"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=32,
                    ),
                ),
                ("priority", models.CharField(default="normal", max_length=16)),
                ("submitted_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("ack_deadline", models.DateTimeField(db_index=True)),
                ("resolution_deadline", models.DateTimeField(db_index=True)),
                ("breach_ack", models.BooleanField(default=False)),
                ("breach_resolution", models.BooleanField(default=False)),
                ("breach_reason", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upheld", "Upheld"),
                            ("rejected", "Rejected"),
                            ("partial", "Partially upheld"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=32,
                    ),
                ),
                ("outcome_notes", models.TextField(blank=True)),
                ("refund_amount_minor", models.BigIntegerField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_disputes",
                        to="disputeshield.agent",
                    ),
                ),
                (
                    "clock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute",
                        to="disputeshield.slaclock",
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.slapolicyversion",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_dispute",
            },
        ),
        migrations.CreateModel(
            name="DisputeMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.message_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "author_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("agent", "Agent"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("author_id", models.CharField(blank=True, max_length=64)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("customer", "Visible to the customer"),
                            ("internal", "Internal only"),
                        ],
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_disputemessage",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.idempotency_record_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("endpoint", models.CharField(max_length=128)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_idempotencyrecord",
            },
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["tenant", "status", "resolution_deadline"],
                name="disputeshie_tenant__d73f39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["tenant", "assigned_to", "status"], name="disputeshie_tenant__73ba07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["tenant", "customer_ref_hash", "status"],
                name="disputeshie_tenant__abacd5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reference"), name="uniq_dispute_reference_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="disputemessage",
            index=models.Index(
                fields=["tenant", "dispute", "visibility"], name="disputeshie_tenant__94e5f7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="uniq_idempotency_key_per_tenant"
            ),
        ),
    ]
