# Generated by Django 5.2.17 on 2026-08-23 23:00

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.models.widget


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0008_apikey_bootstrap_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="kind",
            field=models.CharField(
                choices=[
                    ("secret", "Secret — server-side only"),
                    ("publishable", "Publishable — safe to embed in a public page"),
                ],
                default="secret",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="AllowedOrigin",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.models.widget.allowed_origin_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_allowedorigin",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "origin"), name="uniq_origin_per_tenant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WidgetConfig",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.models.widget.widget_config_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("primary_colour", models.CharField(default="#0B5FFF", max_length=9)),
                ("radius", models.CharField(default="8px", max_length=8)),
                ("logo_url", models.URLField(blank=True)),
                ("position", models.CharField(default="bottom-right", max_length=16)),
                ("locale", models.CharField(default="en", max_length=8)),
                ("categories", models.JSONField(default=list)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_widgetconfig",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant",), name="uniq_widget_config_per_tenant"
                    )
                ],
            },
        ),
    ]
