# Generated by Django 5.2.17 on 2026-08-23 23:56

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.models.attachment


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0010_widget_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisputeAttachment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.models.attachment.attachment_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("uploaded_by_type", models.CharField(max_length=16)),
                ("uploaded_by_id", models.CharField(blank=True, max_length=64)),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=128)),
                ("size_bytes", models.PositiveIntegerField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("storage_key", models.CharField(max_length=512)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting scan"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("failed", "Scan failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("scan_detail", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_disputeattachment",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "dispute", "scan_status"],
                        name="disputeshie_tenant__447c1c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResponseTemplate",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.models.attachment.template_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("category", models.CharField(blank=True, max_length=64)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_responsetemplate",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "name"), name="uniq_template_name_per_tenant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TransactionContext",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.models.attachment.context_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField()),
                ("summary", models.CharField(max_length=255)),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="context_entries",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_transactioncontext",
                "ordering": ["occurred_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "dispute", "occurred_at"],
                        name="disputeshie_tenant__82210a_idx",
                    )
                ],
            },
        ),
    ]
