# Generated by Django 5.2.17 on 2026-08-24 00:17

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0012_attachment_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditCheckpoint",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.checkpoint_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence_from", models.BigIntegerField()),
                ("sequence_to", models.BigIntegerField()),
                ("record_count", models.BigIntegerField()),
                ("head_hash", models.CharField(max_length=71)),
                ("verified", models.BooleanField()),
                ("failure_detail", models.TextField(blank=True)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("signature", models.CharField(max_length=128)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_auditcheckpoint",
                "ordering": ["tenant_id", "-sequence_to"],
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "sequence_to"), name="uniq_checkpoint_per_tenant_head"
                    )
                ],
            },
        ),
    ]
