# Generated by Django 5.2.17 on 2026-08-24 00:55

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0014_checkpoint_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.incident_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("customer_message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("declared", "Declared"),
                            ("mitigating", "Mitigating"),
                            ("resolved", "Resolved"),
                        ],
                        default="declared",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("expected_resolution_at", models.DateTimeField(blank=True, null=True)),
                ("match_categories", models.JSONField(default=list)),
                ("match_transaction_prefixes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_incident",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentSubscription",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.membership_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_ref_hash", models.CharField(db_index=True, max_length=64)),
                ("transaction_ref", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="disputeshield.incident",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_incidentsubscription",
            },
        ),
        migrations.CreateModel(
            name="IngestAddress",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.ingest_address_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("widget", "Widget"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("ussd", "USSD"),
                            ("phone", "Phone call"),
                            ("social", "Social media"),
                            ("web_form", "Web form"),
                        ],
                        max_length=16,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_ingestaddress",
            },
        ),
        migrations.CreateModel(
            name="MassEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.mass_event_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("root_cause", models.TextField(blank=True)),
                ("finding", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("investigating", "Investigating"),
                            ("applied", "Outcome applied"),
                        ],
                        default="investigating",
                        max_length=16,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("applied_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_massevent",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MassEventMembership",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.membership_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("added_by", models.CharField(blank=True, max_length=64)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("removed_by", models.CharField(blank=True, max_length=64)),
                ("removal_reason", models.CharField(blank=True, max_length=255)),
                ("outcome_applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mass_memberships",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "mass_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="disputeshield.massevent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_masseventmembership",
            },
        ),
        migrations.CreateModel(
            name="DisputeContact",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.contact_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("widget", "Widget"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("ussd", "USSD"),
                            ("phone", "Phone call"),
                            ("social", "Social media"),
                            ("web_form", "Web form"),
                        ],
                        max_length=16,
                    ),
                ),
                ("identity_hash", models.CharField(db_index=True, max_length=64)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_disputecontact",
                "indexes": [
                    models.Index(
                        fields=["tenant", "channel", "identity_hash"],
                        name="disputeshie_tenant__08d042_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dispute", "channel", "identity_hash"),
                        name="uniq_contact_per_channel",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InboundMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.inbound_message_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("widget", "Widget"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("ussd", "USSD"),
                            ("phone", "Phone call"),
                            ("social", "Social media"),
                            ("web_form", "Web form"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("from_identity_hash", models.CharField(db_index=True, max_length=64)),
                ("thread_key_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("received_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("matched", "Appended to a case"),
                            ("filed", "Opened a new case"),
                            ("unmatched_review", "Needs a human to attribute"),
                            ("quarantined", "Sender is not the case's verified contact"),
                            ("ignored", "Auto-reply, bounce or duplicate"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("state_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_messages",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_inboundmessage",
                "ordering": ["received_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "state", "received_at"],
                        name="disputeshie_tenant__e98376_idx",
                    ),
                    models.Index(
                        fields=["tenant", "channel", "thread_key_hash"],
                        name="disputeshie_tenant__c0baec_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["tenant", "status", "started_at"], name="disputeshie_tenant__fc8b4c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="incidentsubscription",
            constraint=models.UniqueConstraint(
                fields=("incident", "customer_ref_hash", "transaction_ref"),
                name="uniq_subscription_per_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestaddress",
            constraint=models.UniqueConstraint(
                fields=("channel", "address"), name="uniq_ingest_address"
            ),
        ),
        migrations.AddIndex(
            model_name="masseventmembership",
            index=models.Index(
                fields=["tenant", "mass_event", "removed_at"], name="disputeshie_tenant__ae4a01_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="masseventmembership",
            constraint=models.UniqueConstraint(
                fields=("mass_event", "dispute"), name="uniq_membership_per_case"
            ),
        ),
    ]
