# Generated by Django 5.2.17 on 2026-08-24 01:40

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0016_intake_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErasureRequest",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.erasure_request_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_ref_hash", models.CharField(db_index=True, max_length=64)),
                ("requested_at", models.DateTimeField()),
                ("requested_via", models.CharField(blank=True, max_length=64)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("refused_legal_hold", "Refused — material is under legal hold"),
                            ("refused_retention", "Refused — regulatory retention applies"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("outcome_reason", models.TextField(blank=True)),
                ("blocking_holds", models.JSONField(default=list)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_erasurerequest",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalEscalation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.escalation_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        choices=[
                            ("regulator", "Regulator's consumer protection desk"),
                            ("ombudsman", "Ombudsman"),
                            ("court", "Court"),
                            ("scheme", "Card scheme"),
                        ],
                        max_length=16,
                    ),
                ),
                ("external_reference", models.CharField(max_length=128)),
                ("opened_at", models.DateTimeField()),
                ("response_due_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "determination",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upheld", "Upheld against the firm"),
                            ("rejected", "Rejected"),
                            ("partial", "Partially upheld"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=16,
                    ),
                ),
                ("determination_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalations",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_externalescalation",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalCorrespondence",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.escalation_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "From the body"), ("outbound", "To the body")],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("summary", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("recorded_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
                (
                    "escalation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correspondence",
                        to="disputeshield.externalescalation",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_externalcorrespondence",
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="LegalHold",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.legal_hold_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "matter_reference",
                    models.CharField(
                        help_text="The litigation, investigation or regulatory matter this serves.",
                        max_length=128,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("dispute", "One case"),
                            ("customer", "Every case for one customer"),
                            ("category", "Every case in a category"),
                            ("period", "Every case filed in a period"),
                        ],
                        max_length=16,
                    ),
                ),
                ("customer_ref_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("category", models.CharField(blank=True, max_length=64)),
                ("period_from", models.DateTimeField(blank=True, null=True)),
                ("period_to", models.DateTimeField(blank=True, null=True)),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("placed_by", models.CharField(max_length=64)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("released_by", models.CharField(blank=True, max_length=64)),
                ("release_reason", models.TextField(blank=True)),
                ("release_approved_by", models.CharField(blank=True, max_length=64)),
                (
                    "dispute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_holds",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_legalhold",
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnTemplate",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.return_template_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="e.g. cbn-consumer-complaints", max_length=64)),
                ("version", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("jurisdiction", models.CharField(blank=True, max_length=64)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=16,
                    ),
                ),
                ("regulatory_reference", models.CharField(blank=True, max_length=255)),
                ("rows", models.JSONField(default=list)),
                ("effective_from", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_returntemplate",
                "ordering": ["code", "-version"],
            },
        ),
        migrations.CreateModel(
            name="RegulatoryReturn",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.regulatory_return_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_from", models.DateTimeField()),
                ("period_to", models.DateTimeField()),
                ("rows", models.JSONField(default=list)),
                ("content_digest", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Generated, awaiting review"),
                            ("approved", "Approved for filing"),
                            ("superseded", "Replaced by a later generation"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("generated_at", models.DateTimeField()),
                ("generated_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approval_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="disputeshield.returntemplate",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_regulatoryreturn",
                "ordering": ["-period_from", "-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckpointAnchor",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.anchor_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checkpoint_id", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting the timestamp authority"),
                            ("anchored", "Timestamped"),
                            ("failed", "Rejected by the authority"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("authority", models.CharField(blank=True, max_length=128)),
                ("token", models.TextField(blank=True)),
                ("anchored_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_checkpointanchor",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "created_at"],
                        name="disputeshie_tenant__bd3689_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="externalescalation",
            index=models.Index(
                fields=["tenant", "closed_at", "response_due_at"],
                name="disputeshie_tenant__b420b4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalescalation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "body", "external_reference"),
                name="uniq_escalation_reference_per_body",
            ),
        ),
        migrations.AddIndex(
            model_name="legalhold",
            index=models.Index(
                fields=["tenant", "scope", "released_at"], name="disputeshie_tenant__189e9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalhold",
            index=models.Index(
                fields=["tenant", "released_at"], name="disputeshie_tenant__e57869_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="returntemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code", "version"), name="uniq_return_template_version"
            ),
        ),
        migrations.AddIndex(
            model_name="regulatoryreturn",
            index=models.Index(
                fields=["tenant", "status", "period_from"], name="disputeshie_tenant__1b15d2_idx"
            ),
        ),
    ]
