# Generated by Django 5.2.17 on 2026-08-24 09:50

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0018_evidence_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="sladeadline",
            name="pausable",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="sladeadline",
            name="kind",
            field=models.CharField(
                choices=[
                    ("acknowledgement", "Acknowledgement due"),
                    ("resolution", "Resolution due"),
                    ("warning", "Warning threshold"),
                    ("auto_close", "Auto-close due"),
                    ("reopen_window", "Reopen window expires"),
                    ("scheme_representment", "Scheme representment due"),
                    ("scheme_warning", "Scheme warning threshold"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ProviderConnector",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.connector_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("paystack", "Paystack"),
                            ("flutterwave", "Flutterwave"),
                            ("nibss", "NIBSS"),
                            ("stripe", "Stripe"),
                            ("generic", "Generic REST"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=128)),
                ("base_url", models.URLField(blank=True)),
                ("credential_ciphertext", models.BinaryField()),
                ("credential_key_ref", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_providerconnector",
            },
        ),
        migrations.CreateModel(
            name="ProviderCall",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.provider_call_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=512)),
                ("request_summary", models.JSONField(default=dict)),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("ok", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_calls",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calls",
                        to="disputeshield.providerconnector",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_providercall",
                "ordering": ["-occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReasonCode",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.representment_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("verve", "Verve"),
                        ],
                        max_length=16,
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("title", models.CharField(max_length=255)),
                ("evidence_requirements", models.JSONField(default=list)),
                ("response_window_days", models.PositiveSmallIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_reasoncode",
                "ordering": ["scheme", "code"],
            },
        ),
        migrations.CreateModel(
            name="Representment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.representment_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chargeback_reference", models.CharField(max_length=128)),
                ("chargeback_at", models.DateTimeField()),
                ("respond_by", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("gathering", "Gathering evidence"),
                            ("ready", "Ready to export"),
                            ("exported", "Pack exported"),
                            ("recorded_submitted", "Recorded as submitted by the fintech"),
                            ("accepted", "Accepted by the scheme"),
                            ("declined", "Declined by the scheme"),
                            ("expired", "Window closed without a response"),
                        ],
                        db_index=True,
                        default="gathering",
                        max_length=24,
                    ),
                ),
                ("evidence", models.JSONField(default=dict)),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("outcome_at", models.DateTimeField(blank=True, null=True)),
                ("outcome_detail", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                (
                    "dispute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="representment",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "reason_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.reasoncode",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_representment",
                "ordering": ["respond_by"],
            },
        ),
        migrations.CreateModel(
            name="SettlementConfirmation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.settlement_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=128)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("settled_at", models.DateTimeField()),
                ("source", models.CharField(default="ledger", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_settlementconfirmation",
                "ordering": ["settled_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="providerconnector",
            constraint=models.UniqueConstraint(
                fields=("tenant", "provider"), name="uniq_connector_per_provider"
            ),
        ),
        migrations.AddIndex(
            model_name="providercall",
            index=models.Index(
                fields=["tenant", "connector", "occurred_at"], name="disputeshie_tenant__e6b381_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reasoncode",
            constraint=models.UniqueConstraint(
                fields=("tenant", "scheme", "code"), name="uniq_reason_code_per_scheme"
            ),
        ),
        migrations.AddIndex(
            model_name="representment",
            index=models.Index(
                fields=["tenant", "status", "respond_by"], name="disputeshie_tenant__771f3e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementconfirmation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reference"), name="uniq_settlement_reference"
            ),
        ),
    ]
