# Generated by Django 5.2.17 on 2026-08-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0020_money_row_level_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reasoncode",
            name="evidence_requirements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="representment",
            name="evidence",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
