# Generated by Django 5.2.17 on 2026-08-24 12:08

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0021_alter_reasoncode_evidence_requirements_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskSignal",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.signal_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("repeat_claimant", "Unusual claim frequency for this customer"),
                            ("rapid_filing", "Filed unusually soon after delivery"),
                            ("cross_provider", "Non-receipt claimed across many providers"),
                        ],
                        max_length=24,
                    ),
                ),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("summary", models.CharField(max_length=255)),
                ("model_id", models.CharField(blank=True, max_length=64)),
                ("model_version", models.CharField(blank=True, max_length=32)),
                ("computed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_signals",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_risksignal",
                "ordering": ["-computed_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dispute", "kind"), name="uniq_risk_signal_per_kind"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RootCauseCluster",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.cluster_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("basis", models.CharField(max_length=64)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("case_count", models.PositiveIntegerField(default=0)),
                ("exposure_minor", models.BigIntegerField(default=0)),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("computed_at", models.DateTimeField()),
                ("model_id", models.CharField(blank=True, max_length=64)),
                ("model_version", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_rootcausecluster",
                "ordering": ["-case_count", "label"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "computed_at"], name="disputeshie_tenant__e78d78_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.suggestion_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("category", "Category"),
                            ("subcategory", "Subcategory"),
                            ("priority", "Priority"),
                            ("assignee", "Assignee"),
                            ("reply_draft", "Reply draft"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("value", models.TextField()),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("rationale", models.TextField(blank=True)),
                ("model_id", models.CharField(max_length=64)),
                ("model_version", models.CharField(max_length=32)),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("pending", "Not yet decided"),
                            ("accepted", "Accepted as proposed"),
                            ("overridden", "Human chose something else"),
                            ("discarded", "Discarded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("chosen_value", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suggestions",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_suggestion",
                "ordering": ["-created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "kind", "disposition"],
                        name="disputeshie_tenant__14dbff_idx",
                    ),
                    models.Index(
                        fields=["tenant", "model_id", "model_version"],
                        name="disputeshie_tenant__f0ab5d_idx",
                    ),
                ],
            },
        ),
    ]
