# Generated by Django 5.2.17 on 2026-08-24 12:49

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0022_risksignal_rootcausecluster_suggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.webhook_endpoint_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                ("description", models.CharField(blank=True, max_length=128)),
                ("event_types", models.JSONField(blank=True, default=list)),
                ("signing_secret", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_webhookendpoint",
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.webhook_delivery_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("sequence_key", models.CharField(db_index=True, max_length=64)),
                ("sequence", models.BigIntegerField(default=0)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("parked", "Parked after exhausting retries"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="disputeshield.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_webhookdelivery",
                "ordering": ["sequence_key", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="PolicySimulation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.simulation_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("proposed", models.JSONField(blank=True, default=dict)),
                ("period_from", models.DateTimeField()),
                ("period_to", models.DateTimeField()),
                ("cases_examined", models.PositiveIntegerField(default=0)),
                ("actual_breaches", models.PositiveIntegerField(default=0)),
                ("projected_breaches", models.PositiveIntegerField(default=0)),
                ("by_category", models.JSONField(blank=True, default=dict)),
                ("by_agent", models.JSONField(blank=True, default=dict)),
                ("ran_at", models.DateTimeField()),
                ("ran_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulations",
                        to="disputeshield.slapolicyversion",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_policysimulation",
                "ordering": ["-ran_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "policy_version", "ran_at"],
                        name="disputeshie_tenant__319949_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QaReview",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.qa_review_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_id", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("sampled", "Randomly sampled"),
                            ("forced", "Met a forced-review criterion"),
                        ],
                        max_length=16,
                    ),
                ),
                ("forced_reason", models.CharField(blank=True, max_length=128)),
                ("scores", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=64)),
                ("agent_response", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qa_reviews",
                        to="disputeshield.dispute",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_qareview",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "agent_id", "reviewed_at"],
                        name="disputeshie_tenant__7495df_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("dispute",), name="uniq_qa_review_per_case")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="webhookendpoint",
            constraint=models.UniqueConstraint(
                fields=("tenant", "url"), name="uniq_webhook_url_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["next_attempt_at"],
                name="idx_pending_deliveries",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["tenant", "sequence_key", "sequence"], name="disputeshie_tenant__0712f8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookdelivery",
            constraint=models.UniqueConstraint(
                fields=("tenant", "endpoint", "idempotency_key"),
                name="uniq_delivery_per_endpoint_event",
            ),
        ),
    ]
