# Generated by Django 5.2.17 on 2026-08-24 13:28

import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0024_operations_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="clock_offset_seconds",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="content_sealing_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="environment",
            field=models.CharField(
                choices=[("test", "Test"), ("live", "Live")],
                db_index=True,
                default="live",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="region",
            field=models.CharField(db_index=True, default="eu-west-1", max_length=32),
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.import_batch_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("zendesk", "Zendesk"),
                            ("freshdesk", "Freshdesk"),
                            ("intercom", "Intercom"),
                            ("csv", "CSV export"),
                            ("mailbox", "IMAP archive"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("source_digest", models.CharField(blank=True, max_length=64)),
                ("imported_at", models.DateTimeField()),
                ("imported_by", models.CharField(blank=True, max_length=64)),
                ("cases_imported", models.PositiveIntegerField(default=0)),
                ("cases_rejected", models.PositiveIntegerField(default=0)),
                ("rejections", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_importbatch",
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="SubjectKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.subject_key_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_hash", models.CharField(db_index=True, max_length=64)),
                ("wrapped_key", models.BinaryField()),
                ("master_key_ref", models.CharField(blank=True, max_length=128)),
                ("destroyed_at", models.DateTimeField(blank=True, null=True)),
                ("destroyed_by", models.CharField(blank=True, max_length=64)),
                ("destruction_approved_by", models.CharField(blank=True, max_length=64)),
                ("destruction_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_subjectkey",
                "indexes": [
                    models.Index(
                        fields=["tenant", "destroyed_at"], name="disputeshie_tenant__78dfda_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "subject_hash"), name="uniq_key_per_subject"
                    )
                ],
            },
        ),
    ]
