# Generated by Django 5.2.17 on 2026-08-24 14:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0026_residency_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportRecipient",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.report_recipient_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "address",
                    models.EmailField(
                        max_length=254, validators=[django.core.validators.EmailValidator()]
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                ("added_by", models.CharField(max_length=64)),
                ("reason", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_by", models.CharField(blank=True, max_length=64)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_reportrecipient",
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"], name="disputeshie_tenant__2c43db_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "address"),
                        name="disputeshield_recipient_unique_per_tenant",
                    )
                ],
            },
        ),
    ]
