# Generated by Django 5.2.17 on 2026-08-24 15:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import disputeshield.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("disputeshield", "0028_report_recipient_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=disputeshield.identifiers.report_schedule_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("recipients", models.JSONField(default=list)),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "hour",
                    models.PositiveSmallIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                ("timezone_name", models.CharField(default="UTC", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.CharField(max_length=64)),
                ("reason", models.CharField(max_length=255)),
                ("last_period_start", models.DateField(blank=True, null=True)),
                ("failed_periods", models.JSONField(default=list)),
                ("deactivated_by", models.CharField(blank=True, max_length=64)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="disputeshield.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "disputeshield_reportschedule",
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"], name="disputeshie_tenant__7a473f_idx"
                    )
                ],
            },
        ),
    ]
